//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luval.Security.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Hydrogen</string>\r\n  <string>Helium</string>\r\n  <string>Lithium</string>\r\n" +
            "  <string>Beryllium</string>\r\n  <string>Boron</string>\r\n  <string>Carbon</string" +
            ">\r\n  <string>Nitrogen</string>\r\n  <string>Oxygen</string>\r\n  <string>Fluorine</s" +
            "tring>\r\n  <string>Neon</string>\r\n  <string>Sodium</string>\r\n  <string>Magnesium<" +
            "/string>\r\n  <string>Aluminium</string>\r\n  <string>Silicon</string>\r\n  <string>Ph" +
            "osphorus</string>\r\n  <string>Sulfur</string>\r\n  <string>Chlorine</string>\r\n  <st" +
            "ring>Argon</string>\r\n  <string>Potassium</string>\r\n  <string>Calcium</string>\r\n " +
            " <string>Scandium</string>\r\n  <string>Titanium</string>\r\n  <string>Vanadium</str" +
            "ing>\r\n  <string>Chromium</string>\r\n  <string>Manganese</string>\r\n  <string>Iron<" +
            "/string>\r\n  <string>Cobalt</string>\r\n  <string>Nickel</string>\r\n  <string>Copper" +
            "</string>\r\n  <string>Zinc</string>\r\n  <string>Gallium</string>\r\n  <string>German" +
            "ium</string>\r\n  <string>Arsenic</string>\r\n  <string>Selenium</string>\r\n  <string" +
            ">Bromine</string>\r\n  <string>Krypton</string>\r\n  <string>Rubidium</string>\r\n  <s" +
            "tring>Strontium</string>\r\n  <string>Yttrium</string>\r\n  <string>Zirconium</strin" +
            "g>\r\n  <string>Niobium</string>\r\n  <string>Molybdenum</string>\r\n  <string>Technet" +
            "ium</string>\r\n  <string>Ruthenium</string>\r\n  <string>Rhodium</string>\r\n  <strin" +
            "g>Palladium</string>\r\n  <string>Silver</string>\r\n  <string>Cadmium</string>\r\n  <" +
            "string>Indium</string>\r\n  <string>Tin</string>\r\n  <string>Antimony</string>\r\n  <" +
            "string>Tellurium</string>\r\n  <string>Iodine</string>\r\n  <string>Xenon</string>\r\n" +
            "  <string>Caesium</string>\r\n  <string>Barium</string>\r\n  <string>Lanthanum</stri" +
            "ng>\r\n  <string>Cerium</string>\r\n  <string>Praseodymium</string>\r\n  <string>Neody" +
            "mium</string>\r\n  <string>Promethium</string>\r\n  <string>Samarium</string>\r\n  <st" +
            "ring>Europium</string>\r\n  <string>Gadolinium</string>\r\n  <string>Terbium</string" +
            ">\r\n  <string>Dysprosium</string>\r\n  <string>Holmium</string>\r\n  <string>Erbium</" +
            "string>\r\n  <string>Thulium</string>\r\n  <string>Ytterbium</string>\r\n  <string>Lut" +
            "etium</string>\r\n  <string>Hafnium</string>\r\n  <string>Tantalum</string>\r\n  <stri" +
            "ng>Tungsten</string>\r\n  <string>Rhenium</string>\r\n  <string>Osmium</string>\r\n  <" +
            "string>Iridium</string>\r\n  <string>Platinum</string>\r\n  <string>Gold</string>\r\n " +
            " <string>Mercury</string>\r\n  <string>Thallium</string>\r\n  <string>Lead</string>\r" +
            "\n  <string>Bismuth</string>\r\n  <string>Polonium</string>\r\n  <string>Astatine</st" +
            "ring>\r\n  <string>Radon</string>\r\n  <string>Francium</string>\r\n  <string>Radium</" +
            "string>\r\n  <string>Actinium</string>\r\n  <string>Thorium</string>\r\n  <string>Prot" +
            "actinium</string>\r\n  <string>Uranium</string>\r\n  <string>Neptunium</string>\r\n  <" +
            "string>Plutonium</string>\r\n  <string>Americium</string>\r\n  <string>Curium</strin" +
            "g>\r\n  <string>Berkelium</string>\r\n  <string>Californium</string>\r\n  <string>Eins" +
            "teinium</string>\r\n  <string>Fermium</string>\r\n  <string>Mendelevium</string>\r\n  " +
            "<string>Nobelium</string>\r\n  <string>Lawrencium</string>\r\n  <string>Rutherfordiu" +
            "m</string>\r\n  <string>Dubnium</string>\r\n  <string>Seaborgium</string>\r\n  <string" +
            ">Bohrium</string>\r\n  <string>Hassium</string>\r\n  <string>Meitnerium</string>\r\n  " +
            "<string>Darmstadtium</string>\r\n  <string>Roentgenium</string>\r\n  <string>Coperni" +
            "cium</string>\r\n  <string>Ununtrium</string>\r\n  <string>Flerovium</string>\r\n  <st" +
            "ring>Ununpentium</string>\r\n  <string>Livermorium</string>\r\n  <string>Ununseptium" +
            "</string>\r\n  <string>Ununoctium</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PasswordCollection {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PasswordCollection"]));
            }
        }
    }
}
