CREATE TABLE IsoCountry(
IsoCode2 CHAR(2) NOT NULL PRIMARY KEY, 
Name VARCHAR(80) NOT NULL, 
PrintableName VARCHAR(80) NOT NULL, 
IsoCode3 CHAR(3), 
NumericCode SMALLINT );

INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AD','ANDORRA','Andorra','AND',20);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE',784);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AF','AFGHANISTAN','Afghanistan','AFG',4);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG',28);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AI','ANGUILLA','Anguilla','AIA',660);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AL','ALBANIA','Albania','ALB',8);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AM','ARMENIA','Armenia','ARM',51);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AN','NETHERLANDS ANTILLES','Netherlands Antilles','ANT',530);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AO','ANGOLA','Angola','AGO',24);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AQ','ANTARCTICA','Antarctica',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AR','ARGENTINA','Argentina','ARG',32);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AS','AMERICAN SAMOA','American Samoa','ASM',16);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AT','AUSTRIA','Austria','AUT',40);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AU','AUSTRALIA','Australia','AUS',36);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AW','ARUBA','Aruba','ABW',533);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('AZ','AZERBAIJAN','Azerbaijan','AZE',31);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH',70);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BB','BARBADOS','Barbados','BRB',52);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BD','BANGLADESH','Bangladesh','BGD',50);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BE','BELGIUM','Belgium','BEL',56);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BF','BURKINA FASO','Burkina Faso','BFA',854);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BG','BULGARIA','Bulgaria','BGR',100);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BH','BAHRAIN','Bahrain','BHR',48);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BI','BURUNDI','Burundi','BDI',108);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BJ','BENIN','Benin','BEN',204);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BM','BERMUDA','Bermuda','BMU',60);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN',96);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BO','BOLIVIA','Bolivia','BOL',68);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BR','BRAZIL','Brazil','BRA',76);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BS','BAHAMAS','Bahamas','BHS',44);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BT','BHUTAN','Bhutan','BTN',64);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BV','BOUVET ISLAND','Bouvet Island',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BW','BOTSWANA','Botswana','BWA',72);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BY','BELARUS','Belarus','BLR',112);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('BZ','BELIZE','Belize','BLZ',84);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CA','CANADA','Canada','CAN',124);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CC','COCOS (KEELING) ISLANDS','Cocos (Keeling) Islands',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD',180);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF',140);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CG','CONGO','Congo','COG',178);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CH','SWITZERLAND','Switzerland','CHE',756);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CI','COTE D''IVOIRE','Cote D''Ivoire','CIV',384);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CK','COOK ISLANDS','Cook Islands','COK',184);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CL','CHILE','Chile','CHL',152);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CM','CAMEROON','Cameroon','CMR',120);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CN','CHINA','China','CHN',156);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CO','COLOMBIA','Colombia','COL',170);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CR','COSTA RICA','Costa Rica','CRI',188);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CS','SERBIA AND MONTENEGRO','Serbia and Montenegro',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CU','CUBA','Cuba','CUB',192);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CV','CAPE VERDE','Cape Verde','CPV',132);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CX','CHRISTMAS ISLAND','Christmas Island',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CY','CYPRUS','Cyprus','CYP',196);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('CZ','CZECH REPUBLIC','Czech Republic','CZE',203);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('DE','GERMANY','Germany','DEU',276);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('DJ','DJIBOUTI','Djibouti','DJI',262);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('DK','DENMARK','Denmark','DNK',208);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('DM','DOMINICA','Dominica','DMA',212);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('DO','DOMINICAN REPUBLIC','Dominican Republic','DOM',214);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('DZ','ALGERIA','Algeria','DZA',12);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('EC','ECUADOR','Ecuador','ECU',218);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('EE','ESTONIA','Estonia','EST',233);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('EG','EGYPT','Egypt','EGY',818);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('EH','WESTERN SAHARA','Western Sahara','ESH',732);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('ER','ERITREA','Eritrea','ERI',232);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('ES','SPAIN','Spain','ESP',724);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('ET','ETHIOPIA','Ethiopia','ETH',231);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('FI','FINLAND','Finland','FIN',246);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('FJ','FIJI','Fiji','FJI',242);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('FK','FALKLAND ISLANDS (MALVINAS)','Falkland Islands (Malvinas)','FLK',238);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('FM','MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM',583);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('FO','FAROE ISLANDS','Faroe Islands','FRO',234);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('FR','FRANCE','France','FRA',250);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GA','GABON','Gabon','GAB',266);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GB','UNITED KINGDOM','United Kingdom','GBR',826);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GD','GRENADA','Grenada','GRD',308);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GE','GEORGIA','Georgia','GEO',268);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GF','FRENCH GUIANA','French Guiana','GUF',254);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GH','GHANA','Ghana','GHA',288);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GI','GIBRALTAR','Gibraltar','GIB',292);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GL','GREENLAND','Greenland','GRL',304);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GM','GAMBIA','Gambia','GMB',270);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GN','GUINEA','Guinea','GIN',324);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GP','GUADELOUPE','Guadeloupe','GLP',312);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ',226);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GR','GREECE','Greece','GRC',300);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','South Georgia and the South Sandwich Islands',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GT','GUATEMALA','Guatemala','GTM',320);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GU','GUAM','Guam','GUM',316);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GW','GUINEA-BISSAU','Guinea-Bissau','GNB',624);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('GY','GUYANA','Guyana','GUY',328);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('HK','HONG KONG','Hong Kong','HKG',344);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('HM','HEARD ISLAND AND MCDONALD ISLANDS','Heard Island and Mcdonald Islands',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('HN','HONDURAS','Honduras','HND',340);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('HR','CROATIA','Croatia','HRV',191);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('HT','HAITI','Haiti','HTI',332);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('HU','HUNGARY','Hungary','HUN',348);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('ID','INDONESIA','Indonesia','IDN',360);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('IE','IRELAND','Ireland','IRL',372);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('IL','ISRAEL','Israel','ISR',376);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('IN','INDIA','India','IND',356);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('IO','BRITISH INDIAN OCEAN TERRITORY','British Indian Ocean Territory',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('IQ','IRAQ','Iraq','IRQ',368);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN',364);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('IS','ICELAND','Iceland','ISL',352);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('IT','ITALY','Italy','ITA',380);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('JM','JAMAICA','Jamaica','JAM',388);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('JO','JORDAN','Jordan','JOR',400);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('JP','JAPAN','Japan','JPN',392);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KE','KENYA','Kenya','KEN',404);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KG','KYRGYZSTAN','Kyrgyzstan','KGZ',417);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KH','CAMBODIA','Cambodia','KHM',116);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KI','KIRIBATI','Kiribati','KIR',296);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KM','COMOROS','Comoros','COM',174);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KN','SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA',659);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','Korea, Democratic People''s Republic of','PRK',408);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KR','KOREA, REPUBLIC OF','Korea, Republic of','KOR',410);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KW','KUWAIT','Kuwait','KWT',414);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KY','CAYMAN ISLANDS','Cayman Islands','CYM',136);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('KZ','KAZAKHSTAN','Kazakhstan','KAZ',398);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC','Lao People''s Democratic Republic','LAO',418);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LB','LEBANON','Lebanon','LBN',422);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LC','SAINT LUCIA','Saint Lucia','LCA',662);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LI','LIECHTENSTEIN','Liechtenstein','LIE',438);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LK','SRI LANKA','Sri Lanka','LKA',144);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LR','LIBERIA','Liberia','LBR',430);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LS','LESOTHO','Lesotho','LSO',426);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LT','LITHUANIA','Lithuania','LTU',440);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LU','LUXEMBOURG','Luxembourg','LUX',442);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LV','LATVIA','Latvia','LVA',428);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY',434);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MA','MOROCCO','Morocco','MAR',504);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MC','MONACO','Monaco','MCO',492);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA',498);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MG','MADAGASCAR','Madagascar','MDG',450);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MH','MARSHALL ISLANDS','Marshall Islands','MHL',584);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia, the Former Yugoslav Republic of','MKD',807);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('ML','MALI','Mali','MLI',466);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MM','MYANMAR','Myanmar','MMR',104);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MN','MONGOLIA','Mongolia','MNG',496);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MO','MACAO','Macao','MAC',446);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MP','NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP',580);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MQ','MARTINIQUE','Martinique','MTQ',474);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MR','MAURITANIA','Mauritania','MRT',478);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MS','MONTSERRAT','Montserrat','MSR',500);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MT','MALTA','Malta','MLT',470);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MU','MAURITIUS','Mauritius','MUS',480);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MV','MALDIVES','Maldives','MDV',462);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MW','MALAWI','Malawi','MWI',454);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MX','MEXICO','Mexico','MEX',484);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MY','MALAYSIA','Malaysia','MYS',458);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('MZ','MOZAMBIQUE','Mozambique','MOZ',508);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NA','NAMIBIA','Namibia','NAM',516);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NC','NEW CALEDONIA','New Caledonia','NCL',540);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NE','NIGER','Niger','NER',562);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NF','NORFOLK ISLAND','Norfolk Island','NFK',574);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NG','NIGERIA','Nigeria','NGA',566);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NI','NICARAGUA','Nicaragua','NIC',558);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NL','NETHERLANDS','Netherlands','NLD',528);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NO','NORWAY','Norway','NOR',578);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NP','NEPAL','Nepal','NPL',524);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NR','NAURU','Nauru','NRU',520);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NU','NIUE','Niue','NIU',570);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('NZ','NEW ZEALAND','New Zealand','NZL',554);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('OM','OMAN','Oman','OMN',512);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PA','PANAMA','Panama','PAN',591);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PE','PERU','Peru','PER',604);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PF','FRENCH POLYNESIA','French Polynesia','PYF',258);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PG','PAPUA NEW GUINEA','Papua New Guinea','PNG',598);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PH','PHILIPPINES','Philippines','PHL',608);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PK','PAKISTAN','Pakistan','PAK',586);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PL','POLAND','Poland','POL',616);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PM','SAINT PIERRE AND MIQUELON','Saint Pierre and Miquelon','SPM',666);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PN','PITCAIRN','Pitcairn','PCN',612);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PR','PUERTO RICO','Puerto Rico','PRI',630);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PS','PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PT','PORTUGAL','Portugal','PRT',620);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PW','PALAU','Palau','PLW',585);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('PY','PARAGUAY','Paraguay','PRY',600);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('QA','QATAR','Qatar','QAT',634);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('RE','REUNION','Reunion','REU',638);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('RO','ROMANIA','Romania','ROM',642);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('RU','RUSSIAN FEDERATION','Russian Federation','RUS',643);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('RW','RWANDA','Rwanda','RWA',646);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SA','SAUDI ARABIA','Saudi Arabia','SAU',682);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SB','SOLOMON ISLANDS','Solomon Islands','SLB',90);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SC','SEYCHELLES','Seychelles','SYC',690);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SD','SUDAN','Sudan','SDN',736);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SE','SWEDEN','Sweden','SWE',752);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SG','SINGAPORE','Singapore','SGP',702);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SH','SAINT HELENA','Saint Helena','SHN',654);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SI','SLOVENIA','Slovenia','SVN',705);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SJ','SVALBARD AND JAN MAYEN','Svalbard and Jan Mayen','SJM',744);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SK','SLOVAKIA','Slovakia','SVK',703);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SL','SIERRA LEONE','Sierra Leone','SLE',694);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SM','SAN MARINO','San Marino','SMR',674);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SN','SENEGAL','Senegal','SEN',686);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SO','SOMALIA','Somalia','SOM',706);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SR','SURINAME','Suriname','SUR',740);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('ST','SAO TOME AND PRINCIPE','Sao Tome and Principe','STP',678);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SV','EL SALVADOR','El Salvador','SLV',222);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR',760);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('SZ','SWAZILAND','Swaziland','SWZ',748);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TC','TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA',796);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TD','CHAD','Chad','TCD',148);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TF','FRENCH SOUTHERN TERRITORIES','French Southern Territories',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TG','TOGO','Togo','TGO',768);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TH','THAILAND','Thailand','THA',764);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TJ','TAJIKISTAN','Tajikistan','TJK',762);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TK','TOKELAU','Tokelau','TKL',772);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TL','TIMOR-LESTE','Timor-Leste',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TM','TURKMENISTAN','Turkmenistan','TKM',795);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TN','TUNISIA','Tunisia','TUN',788);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TO','TONGA','Tonga','TON',776);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TR','TURKEY','Turkey','TUR',792);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO',780);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TV','TUVALU','Tuvalu','TUV',798);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TW','TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN',158);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA',834);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('UA','UKRAINE','Ukraine','UKR',804);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('UG','UGANDA','Uganda','UGA',800);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('UM','UNITED STATES MINOR OUTLYING ISLANDS','United States Minor Outlying Islands',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('US','UNITED STATES','United States','USA',840);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('UY','URUGUAY','Uruguay','URY',858);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('UZ','UZBEKISTAN','Uzbekistan','UZB',860);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('VA','HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT',336);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('VC','SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT',670);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('VE','VENEZUELA','Venezuela','VEN',862);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('VG','VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB',92);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('VI','VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR',850);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('VN','VIET NAM','Viet Nam','VNM',704);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('VU','VANUATU','Vanuatu','VUT',548);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('WF','WALLIS AND FUTUNA','Wallis and Futuna','WLF',876);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('WS','SAMOA','Samoa','WSM',882);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('YE','YEMEN','Yemen','YEM',887);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('YT','MAYOTTE','Mayotte',NULL,NULL);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('ZA','SOUTH AFRICA','South Africa','ZAF',710);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('ZM','ZAMBIA','Zambia','ZMB',894);
INSERT INTO IsoCountry (IsoCode2, Name, PrintableName, IsoCode3, NumericCode) VALUES ('ZW','ZIMBABWE','Zimbabwe','ZWE',716);